services:
  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    image: "nginx:alpine"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
    networks:
      - internal

  php:
    container_name: "${PROJECT_NAME}-php"
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - internal

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - docker/mysql/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
